-- Seed files are listed in supabase/config.toml under [db.seed].sql_paths.
-- Add new seed files there instead of using \i (Supabase CLI does not execute
-- psql backslash commands during `db reset`).
